# Generated by Django 4.2.3 on 2023-08-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
