# Generated by Django 4.2.3 on 2023-08-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_block_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
