# Generated by Django 4.2.3 on 2023-08-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_block_subtitle_alter_block_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='style_css',
            field=models.TextField(blank=True, verbose_name='Estilo em CSS'),
        ),
    ]
