# Generated by Django 4.2.3 on 2023-08-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_page_style_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
